In [1]:
import pandas as pd
import numpy as np

url    = "https://home.sis.siam.edu/registrar/student_inclass_all.asp?backto=teach_time&option=1&classid=208419&courseid=14949&acadyear=2564&semester=2&normalURL=f%5Fcmd%3D2%26officercode%3D53113029%26officerid%3D20710%26officername%3D%25BC%25C8%252E%25B4%25C3%252E%2B%25B7%25D1%25C8%25B9%25D1%25C2%2B%25BE%25C5%25CD%25C2%25CA%25D8%25C7%25C3%25C3%25B3%26acadyear%3D2564%26rnd%3D44585%2E5031944444%26firstday%3D24%2F1%2F2565%26semester%3D2&avs652493303=9"
List = pd.read_html(url)

df = List[3]
df =  df.loc[3:,0:2].reset_index( drop = True).drop(0,axis=1)
df['No']     = df.index + 1

df0= df.rename(columns={1:'id',2:'Name'})
df0 =df0[['No','id','Name']]
df0['id']= df0['id'].astype('string')
df = df0

df

    No          id                     Name
0    1  6004200004         นายเนติธร บัวรอด
1    2  6004200016    นายสมรรถชัย เขียวดารา
2    3  6203200006           นายนุห ภู่เงิน
3    4  6203200007       นายธนัช สุทธาทันต์
4    5  6203220002  นายจิรวิทย์ โพธิ์ไพจิตร
5    6  6221200004     นายรวิพล ขำเมืองน้อย
6    7  6223200004    นายธนศักดิ์ จันทรัตน์
7    8  6223200006    นายภัทรพล ศรีเทียนทอง
8    9  6223200010     นายณัฐพงศ์ นาคทรัพย์
9   10  6223200011      นายรตนากร อักษรวรรณ
10  11  6223200012     นายณัฐวุฒิ แก้วประไพ
11  12  6223200013      นายกมลเทพ จิตรณรงค์
12  13  6223200014      นายนิวัฒน์ รัตนสาคร
13  14  6223200019     นายชาคริต เอี่ยมสกุล
14  15  6223200022           นายคมสัน อำนวย
15  16  6223200025          นายจรัญ รักญาติ
16  17  6223200026      นายฐิติกานต์ อิ่มใจ
17  18  6223200027   นายพรพิพัฒน์ กรรฐโรจน์
18  19  6223200028     นายไตรเทพ ภักดิ์ใจดี
19  20  6223200030    นายภูรินทร์ กิติจนาทร
20  21  6223200031      นายกรวุฒิ อิ่มอาดูร
21  22  6223200032   นายพงษ์เพชร พุ่มลอยฟ้า
22  23  6223200033        นางสาวรณิดา นพวัง
23  24  6223220001  นายธีระศักดิ์ จันทร์แมน
24  25  6223220004      นายนนทวัฒน์ บุญเป็ง
25  26  6223220005        นายนิธิ เมฆะวัฒนะ
26  27  6304200016  นายศุภชัย เตชะธนไพบูลย์
27  28  6304200018  นางสาวจุฑามาศ โปณสุวรรณ

In [2]:
groups         = 5


Num_peoples    = len(df) // groups
Remain_people = len(df) % groups
List_groups = []


for i in range(groups) :
    List_groups += Num_peoples*[i+1]
    if Remain_people >0  :
       List_groups.append(i+1)
       Remain_people -= 1


df['groups'] = List_groups
df['Name_groups'] = df['Name']+' กลุ่ม ('+df['groups'].astype('str')+')'
df['groups'] = df['groups'].sample(frac=1).reset_index(drop=True)
df=df.sort_values(by=['groups'])
df = df.reset_index(drop=True)


df

,No,id,Name,groups,Name_groups
0,21,6223200031,นายกรวุฒิ อิ่มอาดูร,1,นายกรวุฒิ อิ่มอาดูร กลุ่ม (4)
1,5,6203220002,นายจิรวิทย์ โพธิ์ไพจิตร,1,นายจิรวิทย์ โพธิ์ไพจิตร กลุ่ม (1)
2,6,6221200004,นายรวิพล ขำเมืองน้อย,1,นายรวิพล ขำเมืองน้อย กลุ่ม (1)
3,19,6223200028,นายไตรเทพ ภักดิ์ใจดี,1,นายไตรเทพ ภักดิ์ใจดี กลุ่ม (4)
4,18,6223200027,นายพรพิพัฒน์ กรรฐโรจน์,1,นายพรพิพัฒน์ กรรฐโรจน์ กลุ่ม (3)
5,12,6223200013,นายกมลเทพ จิตรณรงค์,1,นายกมลเทพ จิตรณรงค์ กลุ่ม (2)
6,1,6004200004,นายเนติธร บัวรอด,2,นายเนติธร บัวรอด กลุ่ม (1)
7,24,6223220001,นายธีระศักดิ์ จันทร์แมน,2,นายธีระศักดิ์ จันทร์แมน กลุ่ม (5)
8,20,6223200030,นายภูรินทร์ กิติจนาทร,2,นายภูรินทร์ กิติจนาทร กลุ่ม (4)
9,15,6223200022,นายคมสัน อำนวย,2,นายคมสัน อำนวย กลุ่ม (3)
10,14,6223200019,นายชาคริต เอี่ยมสกุล,2,นายชาคริต เอี่ยมสกุล กลุ่ม (3)
11,7,6223200004,นายธนศักดิ์ จันทรัตน์,2,นายธนศักดิ์ จันทรัตน์ กลุ่ม (2)
12,13,6223200014,นายนิวัฒน์ รัตนสาคร,3,นายนิวัฒน์ รัตนสาคร กลุ่ม (3)
13,26,6223220005,นายนิธิ เมฆะวัฒนะ,3,นายนิธิ เมฆะวัฒนะ กลุ่ม (5)
14,23,6223200033,นางสาวรณิดา นพวัง,3,นางสาวรณิดา นพวัง กลุ่ม (4)
15,22,6223200032,นายพงษ์เพชร พุ่มลอยฟ้า,3,นายพงษ์เพชร พุ่มลอยฟ้า กลุ่ม (4)
16,3,6203200006,นายนุห ภู่เงิน,3,นายนุห ภู่เงิน กลุ่ม (1)
17,11,6223200012,นายณัฐวุฒิ แก้วประไพ,3,นายณัฐวุฒิ แก้วประไพ กลุ่ม (2)
18,4,6203200007,นายธนัช สุทธาทันต์,4,นายธนัช สุทธาทันต์ กลุ่ม (1)
19,25,6223220004,นายนนทวัฒน์ บุญเป็ง,4,นายนนทวัฒน์ บุญเป็ง กลุ่ม (5)
20,28,6304200018,นางสาวจุฑามาศ โปณสุวรรณ,4,นางสาวจุฑามาศ โปณสุวรรณ กลุ่ม (5)
21,9,6223200010,นายณัฐพงศ์ นาคทรัพย์,4,นายณัฐพงศ์ นาคทรัพย์ กลุ่ม (2)
22,8,6223200006,นายภัทรพล ศรีเทียนทอง,4,นายภัทรพล ศรีเทียนทอง กลุ่ม (2)
23,17,6223200026,นายฐิติกานต์ อิ่มใจ,5,นายฐิติกานต์ อิ่มใจ กลุ่ม (3)
24,16,6223200025,นายจรัญ รักญาติ,5,นายจรัญ รักญาติ กลุ่ม (3)
25,2,6004200016,นายสมรรถชัย เขียวดารา,5,นายสมรรถชัย เขียวดารา กลุ่ม (1)
26,27,6304200016,นายศุภชัย เตชะธนไพบูลย์,5,นายศุภชัย เตชะธนไพบูลย์ กลุ่ม (5)
27,10,6223200011,นายรตนากร อักษรวรรณ,5,นายรตนากร อักษรวรรณ กลุ่ม (2)

In [3]:
df['groups'].value_counts()

1    6
2    6
3    6
4    5
5    5
Name: groups, dtype: int64

In [6]:
df['Name_groups'].to_csv('Group_208419_2564_2.csv',index=False)